### ISSUE TITLE
Typo in Mutillidae service descriptor

### ISSUE THREAD

**Issue by corysabol** [SamuraiWTF/samuraiwtf#100]
https://github.com/SamuraiWTF/samuraiwtf/blob/next/install/targets/mutillidae/mutillidae-tasks.yml#L23

There is a `-` character right after the `=` sign on the line linked above. I have not observed the effects this has on the service, but it's a trivial fix. It's also worth checking the other service descriptors for such errors.

**Comment by secureideas** [comment]
Fixed in Next.
