### ISSUE TITLE
Juice Shop fails to be pulled down on provision

### ISSUE THREAD

**Issue by elreydetoda** [SamuraiWTF/samuraiwtf#102]
On build (`vagrant up` the provisioning step), it appears that Juice shop is failing to get pulled down.
![image](https://user-images.githubusercontent.com/10230166/67140582-e3be6f00-f229-11e9-984b-ec65d89ea3be.png)

Under further investigation it looks like when the following lines get executed:
https://github.com/SamuraiWTF/samuraiwtf/blob/020331702dee702de94b50670edad960db7ebf0b/install/targets/juice-shop/juice-shop-tasks.yml#L12-L19

It greps out the Juice shop we want, but also grabs the md5 sum along with it. As displayed in the picture below. 
![image](https://user-images.githubusercontent.com/10230166/67140597-06e91e80-f22a-11e9-8f4a-3dbef7db914e.png)

Adding a `| grep -v` to the end of this line:
https://github.com/SamuraiWTF/samuraiwtf/blob/master/install/targets/juice-shop/juice-shop-tasks.yml#L17

prevents that from happening. Looks like it could have been introduced ~12 days ago.
![Screenshot_2019-10-19 bkimminich juice-shop](https://user-images.githubusercontent.com/10230166/67143565-9dbdd700-f23a-11e9-8e41-a6e6891287c3.png)

**Comment by secureideas** [comment]
Fixed in Next
