### ISSUE TITLE
make SamuraiWTF bootable

### ISSUE THREAD

**Issue by Ch94Will** [SamuraiWTF/samuraiwtf#133]
Hello.

I woludlike to know if there is a way to make SamuraiWTF .ova file runs on a Flash Memory USB (or external HHD or SSD) like if it was a liveCD or .iso file installed.
I'm asking it because it could improve so much the performance (i prefer it).
i'll wait for your answer.

Regads!

**Comment by secureideas** [comment]
Hi-

Currently the answer is no.  If you know the mechanism to make this work, a pull request would be appreciated.

Kevin

**Comment by JGillam** [comment]
@Ch94Will I'm not sure I understand your question.  An .ova file is just a data file. You can already open such a file in VirtualBox even if it is on Flash Memory or external drive.

This being said, doing so is not likely to gain any performance. Most laptops these days are SSD internal already, so your external drive usually has a slower access rate than internal.
