### ISSUE TITLE
Migrate targets to test TLD

### ISSUE THREAD

**Issue by JGillam** [SamuraiWTF/samuraiwtf#150]
The TLD for targets in this project is currently `wtf.`.  According to [RFC 6761](https://tools.ietf.org/html/rfc6761) the most appropriate TLD for the purpose of this lab is `test.`.  All existing targets should therefore be moved to `test.` and all future targets should be subdomains of  `test.` as well.

**Comment by secureideas** [comment]
First step is done except for musashi and arrrspace.  The changes are in the katana project.   Currently the system supports .wtf and .test.   Once we verify that all of the systems are updated, we can decide to do the next step and remove .wtf.

**Comment by mgillam** [comment]
There may be an issue with this. CA don't issue certs for `.test` TLDs. https://community.letsencrypt.org/t/how-to-generate-certs-for-local-testing-domain-test/60099
As long as there is no *technical* limitation e.g. in OpenSSL preventing us from generating them, I think we're fine. But Samurai needs TLS on the targets more than it needs to use the reserved `.test` TLD specifically.

**Comment by JGillam** [comment]
Huh.... nice catch. We'll have to test that out.  If it doesn't work in our favor, we might be better off just building subdomains off a domain we register.
