### ISSUE TITLE
VMWare Player port

### ISSUE THREAD

**Issue by PNW-Hacker** [SamuraiWTF/samuraiwtf#175]
Downloaded qemu-img for Windows and converted the Hyper-V version to a vmdk extension, then imported it into a new VMWare Player machine, but after booting it, none of the tools are installed, so it likely broke. Was wondering if a pre-built version could be built, please

**Comment by secureideas** [comment]
If you open a shell, is Katana there?  The cli is  #katana list to see what tools it can install/start and what is there.

**Comment by PNW-Hacker** [comment]
Yes, that works :) I will use that option
Maybe this is a separate issue but when I went under Display, there isn't
an option to zoom in, so the Desktop environment is zoomed in better. Is
that normal?

**Comment by secureideas** [comment]
Glad it worked.  Katana is our tooling for application/software management.

As to zooming, I don't have an issue changing resolutions but I am using hyper-v on my development machine.
