### ISSUE TITLE
hostupdater vagrant plugin causes permission errors on windows hosts

### ISSUE THREAD

**Issue by mgillam** [SamuraiWTF/samuraiwtf#2]
It seems to, at least on some boxes, fail to prompt for elevated permissions, so it's unable to open the hosts file. Without the plugin, the module isn't recognized which causes it to fail it. Recommend commenting out that dependency completely, and users can uncomment if they want to use it.

**Comment by secureideas** [comment]
Fixed.  Pushing now.
