### ISSUE TITLE
Guest Additions Failing to load

### ISSUE THREAD

**Issue by JGillam** [SamuraiWTF/samuraiwtf#39]
The fix that was previously introduced appears to no longer be working (see #33 ).

```
An error occurred during installation of VirtualBox Guest Additions 5.2.12. Some functionality may not work as intended.
```

**Comment by JGillam** [comment]
Or maybe not... not sure what is going on here.  I upgraded Vagrant and rebuilt, and it seemed to work.  I would like to get a second opinion on this... anyone else not getting guest additions installing properly when they build it?

**Comment by elreydetoda** [comment]
@JGillam, for me this issue it was solved for me by installing the vbguest plugin, I have version 0.16.0.
https://github.com/SamuraiWTF/samuraiwtf/blob/master/README.md#L14

**Comment by mgillam** [comment]
@elreydetoda https://github.com/SamuraiWTF/samuraiwtf/commit/20ac19e5cfb7feb6623cacb89709cebfcbeb4418
We used to have that.

**Comment by secureideas** [comment]
This appears to be fixed.
