### ISSUE TITLE
Need more flexible terminal

### ISSUE THREAD

**Issue by JGillam** [SamuraiWTF/samuraiwtf#4]
The current xterm (or rather x-terminal-emulator) is somewhat cumbersome.  Considering one of the main goals of SamuraiWTF is as teaching platform, the terminal application needs to be scrollable and zoomable.

The alternative emulator (tilda) might work for this?  If so, it needs to be configured in a way that will work for this.

**Comment by mgillam** [comment]
Since this was opened, the terminal has been switched to Sakura.  Do we need to keep to looking? Or can this be closed?

**Comment by JGillam** [comment]
I haven't checked if Sakura supports zooming in but if that can be confirmed then I am good with closing this issue out.

**Comment by mgillam** [comment]
Just tested and confirmed.  `Ctrl +` and `Ctrl -` are the hotkeys, or you can right-click and manually select font size.

**Comment by mgillam** [comment]
@JGillam I think this one is good to close.

**Comment by JGillam** [comment]
Agreed
