### ISSUE TITLE
Insufficient video memory

### ISSUE THREAD

**Issue by JGillam** [SamuraiWTF/samuraiwtf#45]
The vagrant file is set for 16MB of video memory.  The minimum required to perform full screen mode is 33MB.

**Comment by JGillam** [comment]
Also it seems the re-installation of the guest additions may no longer be necessary.  That issue seems to be resolved as a result of a combination of Vagrant / virtualbox updates and this change.

**Comment by elreydetoda** [comment]
merged and closed #48

**Comment by mgillam** [comment]
I see that this one is still open, but I think you resolved it already @JGillam

**Comment by JGillam** [comment]
yeah, I thought I tagged that on the commit message.
