### ISSUE TITLE
how install in kali linux or docker pull? thanks

### ISSUE THREAD

**Issue by hktalent** [SamuraiWTF/samuraiwtf#60]
how install in kali linux or docker pull? thanks

**Comment by mgillam** [comment]
Samurai is a complete lab, including desktop environment, tools, and local targets. While there are some efforts to make it available on a wider variety of platforms, there is presently no mature model for dockerizing a complete desktop environment, and therefore that is likely not in the future.

The targets could be installed in Kali, although you would end up with a much larger VM with many tools that don't really serve a purpose in the context of web app testing. They are all individual open-source projects (largely maintained by their own respective teams), so I would refer to their documentation for how to install on Kali. You may also find it helpful to look at the Target Bootstrap bash script, found here: https://github.com/SamuraiWTF/samuraiwtf/blob/master/install/target_bootstrap.sh
