### ISSUE TITLE
Consider Moving to CentOS

### ISSUE THREAD

**Issue by JGillam** [SamuraiWTF/samuraiwtf#68]
The Amazon Linux branch seems pretty stable at this point and it makes sense to use a similar structure for other builds (i.e. using Ansible for the build script).  Question is, does it also makes sense to consider moving to Mate on CentOS for the base image?

**Comment by mgillam** [comment]
A half-measure option might be to go to Mate, but leave it on Debian. Ansible playbooks can account for the package managers easily enough, I think, but it would unify the menu system so it's at least not being maintained separately.

**Comment by JGillam** [comment]
Yep.  There's enough extra stuff available in AWS Linux that moving everything to CentOS wouldn't make it as smooth as I had initially hoped anyway.  I think as we move to ansible playbooks for provisioning we can look for opportunities to organize them in such a way that most parts are common between Amazon Linux and a local Vagrant build.

This said, we may also want to consider moving from Debian to Ubuntu if that makes HyperV more likely to work... but that's a future consideration.
