### ISSUE TITLE
dojo basic and scavenger can't connect to their DBs

### ISSUE THREAD

**Issue by JGillam** [SamuraiWTF/samuraiwtf#79]
There's a SQL warning that Host 172.18.0.5 is not allowed to connect to this MySQL server... etc...

**Comment by JGillam** [comment]
It appears that scavenger is working but dojo-basic may need to have the following configuration removed from docker-compose.

```
 volumes:
      - ./src/helpdesk:/var/www/html
```

This would need to be fixed in SamuraiWTF/Samurai-Dojo-legacy

**Comment by secureideas** [comment]
Fixed in next branch
