### ISSUE TITLE
Login credentials not working

### ISSUE THREAD

**Issue by bkimminich** [SamuraiWTF/samuraiwtf#81]
Running SamuraiWTF 4.1.1 on Vagrant on Windows seemingly successfully:
```
Bringing machine 'samuraiwtf' up with 'virtualbox' provider...
==> samuraiwtf: Checking if box 'bento/debian-9' version '201812.27.0' is up to date...
==> samuraiwtf: Clearing any previously set forwarded ports...
==> samuraiwtf: Clearing any previously set network interfaces...
==> samuraiwtf: Preparing network interfaces based on configuration...
    samuraiwtf: Adapter 1: nat
==> samuraiwtf: Forwarding ports...
    samuraiwtf: 22 (guest) => 2222 (host) (adapter 1)
==> samuraiwtf: Running 'pre-boot' VM customizations...
==> samuraiwtf: Booting VM...
==> samuraiwtf: Waiting for machine to boot. This may take a few minutes...
    samuraiwtf: SSH address: 127.0.0.1:2222
    samuraiwtf: SSH username: vagrant
    samuraiwtf: SSH auth method: private key
==> samuraiwtf: Machine booted and ready!
==> samuraiwtf: Checking for guest additions in VM...
==> samuraiwtf: Setting hostname...
==> samuraiwtf: Mounting shared folders...
    samuraiwtf: /vagrant => C:/Data/GitHub/samuraiwtf
    samuraiwtf: /tmp/config => C:/Data/GitHub/samuraiwtf/config
==> samuraiwtf: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> samuraiwtf: flag to force provisioning. Provisioners marked to run always will still run.
```

But I then cannot log in with `samurai`/`samurai`: 
![image](https://user-images.githubusercontent.com/3531020/57494905-d50f7b80-72cb-11e9-8f6f-e0a8e807ab6a.png)

**Comment by mgillam** [comment]
@bkimminich thanks for the issue. Attempting to duplicate. It looks like this was a `vagrant up` on an already provisioned instance. Is there anything you can think of that might have interrupted the provisioning?

**Comment by mgillam** [comment]
I just freshly provisioned an instance an it worked initially. Do you recall what you did? `vagrant up` then `vagrant down` then `vagrant up` again? And this is 4.1.1 from Master, correct?

**Comment by bkimminich** [comment]
I did `vagrant halt` in between. I'll destroy the machine and start from scratch to see if anything disturbed provisioning.

**Comment by bkimminich** [comment]
![image](https://user-images.githubusercontent.com/3531020/57524636-ad9acc00-7328-11e9-8dbf-d11683feed03.png)

Is that normal that the login box already shows up while provisioning is still ongoing... I guess I'll wait until all is done, restart the box and then try logging in for the first time. Let's see how that plays out...

**Comment by secureideas** [comment]
Yes it is normal.  We have looked to see how to hide it, but the base box is running so the log in appears.  I have done this exact thing multiple times and I know that vagrant does it.  :)

**Comment by bkimminich** [comment]
Ok, now it works. "Patience" was the solution... :-D
