### ISSUE TITLE
OVA Link not working

### ISSUE THREAD

**Issue by Rickar04** [SamuraiWTF/samuraiwtf#93]
As of 9/9/19 the link to the OVA in the setup instructions is not working.

**Comment by mgillam** [comment]
Thanks @Rickar04 - we're looking into it.

**Comment by subn3tmasK** [comment]
off topic question.... I’m not having any issues, but wanted to know if I should update Samurai or leave it alone?? Thx

**Comment by secureideas** [comment]
The new version fixes a number of things and moves to an easier platform, so yes I would upgrade.  :)

**Comment by secureideas** [comment]
@mgillam just fixed the link.

**Comment by subn3tmasK** [comment]
thank you!
