### ISSUE TITLE
Critical error during Vagrant Up

### ISSUE THREAD

**Issue by Rickar04** [SamuraiWTF/samuraiwtf#96]
All prerequisites have been met, and this I have installed this successfully before in the past so I am unsure what the issue is. 

Getting critical error:

"Unable to locate package linux-headers-4.9.0.9-amd64"

**Comment by secureideas** [comment]
Which branch are you building?

**Comment by Rickar04** [comment]
I am cloning master

**Comment by secureideas** [comment]
Thanks.  We are looking it internally.  It is odd as the base box should have the right headers installed.  We are looking at adding a fail safe into the build.

Do you mind testing it on the Next branch?

**Comment by Rickar04** [comment]
Happy to help! I will keep an eye out for the update. Samurai WTF is great so I am happy to contribute in any way.

**Comment by secureideas** [comment]
Sorry I should have been clearer.  the Next branch exists right now.  It is where we build after a release.  So currently we are using it for 4.2.1 commits.

**Comment by Rickar04** [comment]
Really sorry. That was my mistake!

I attempted it with Next and got the same error. Scrolling through the
steps I am seeing these errors as well.

[image: image.png]

**Comment by Rickar04** [comment]
Just in case the image didn't come accross. The error is:

http://security.debian.org/debian-security stretch/updates/main amd64 linux-headers-4.9.0-9-common all
404 Not Found [IP: 151.101.204.204 80]
